config/routes.rb
Rails.application.routes.draw do
  root 'file#index'
  resources :file, only: [:index, :create] do 
    collection do 
      get :home
    end
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/merchant.rb
class Merchant < ApplicationRecord
end

app/models/purchase.rb
class Purchase < ApplicationRecord
end

app/models/total_amount.rb
class TotalAmount < ApplicationRecord
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/file_controller.rb
class FileController < ApplicationController
    require 'csv'
    before_action :get_data, only: [:create]
    before_action :set_amounts, only: [:home]

    def index; end

    def create
        service.create_data(data: @data)
    end

    def home; end

    private 

    def get_data
        @data = CSV.open(params[:file], headers: :first_row, col_sep: "\t" ).map(&:to_h)
    end

    def set_amounts
        @last_total_amount = TotalAmount.first.last_total_amount 
        @all_total_amount = TotalAmount.first.all_total_amount
    end
    
    def service
        @service = FileService.new
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/file_helper.rb
module FileHelper
end

app/views/file/home.html.erb
<div class="home-page">
    <div class="wrapper-home">
        <h1 class="last-amount">
        Último valor total inserido: R$
            <%= @last_total_amount %>
        </h1>
        <h1 class="all-amount">
        Valor total geral: R$
            <%= @all_total_amount %>
        </h1>
    </div>
    <div class="back-index">
        <%= button_to "Inserir novo arquivo", file_index_path, method: :get, :class => "btn-back-index" %>
    </div>
</div>

app/views/file/index.html.erb
<html>
  <body>
    <div class="wrapper-main">
    <h1>Importe seu arquivo aqui!</h1>
      <div class="wrapper-form">
        <%= form_with url: file_index_path, multipart: true do |f| %>
            <%= f.file_field(:file, accept: '.tab', align: 'center', required: true, ) %>
            <%# <br><br> %>
            <%= f.submit "Enviar" %>
          <% end %>
        <%= button_to "Ver dados", home_file_index_path, method: :get %>
      </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nuuvem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>